theme: jekyll-theme-cayman
title: Matteo Meli
description: Videogames, coding, kitesurfing and pizza
plugins:
  - jemoji
  - jekyll-seo-tag
theme: jekyll-theme-cayman
repository: matteomeli/matteomeli.github.io
markdown: kramdown
google_analytics: UA-2654146-3
